/* 文件用途：实现转写工作台的配置编辑、上传、任务查询、结果导出和历史交互。 */
'use client';
import { useEffect, useRef, useState } from 'react';
import { createTaskId, copyText } from '@/lib/browser';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Checkbox } from '@/components/ui/checkbox';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { AudioLines, FileAudio, Download, ArrowRight, Copy, LoaderCircle, Eye, EyeOff } from 'lucide-react';

type Segment = { text: string; start_time: number; end_time: number; additions?: { speaker?: string; speaker_id?: string } };
type Result = { result?: { text?: string; utterances?: Segment[] }; audio_info?: { duration?: number } };
type SavedSettings = {key:string;ak:string;sk:string;has_key:boolean;has_ak:boolean;has_sk:boolean;bucket:string;region:string};
type HistoryItem = {id:string;name:string;state:string;created_at:string;preview?:string;characters?:number;text?:string;result?:Result};
const stateLabel:Record<string,string>={done:'已完成',submitted:'已提交',submitting:'提交中',queued:'排队中',running:'识别中',interrupted:'待继续查询'};
const stamp = (ms: number, srt = false) => { const n = Math.max(0, Math.round(ms)); const h = String(Math.floor(n / 3600000)).padStart(2,'0'), m = String(Math.floor(n / 60000) % 60).padStart(2,'0'), s = String(Math.floor(n / 1000) % 60).padStart(2,'0'); return `${h}:${m}:${s}${srt ? ',' + String(n % 1000).padStart(3,'0') : ''}`; };
function SecretField({id,label,value,onChange}:{id:string;label:string;value:string;onChange:(value:string)=>void}) {
 const [shown,setShown]=useState(false);
 return <div className="field"><label htmlFor={id}>{label}</label><div className="secretInput"><Input id={id} type={shown?'text':'password'} autoComplete="off" spellCheck={false} value={value} onChange={e=>onChange(e.target.value)} placeholder={'填写 '+label}/><Button type="button" variant="ghost" className="revealSecret" aria-label={(shown?'隐藏':'显示')+label} aria-pressed={shown} title={shown?'隐藏':'显示'} onClick={()=>setShown(v=>!v)}>{shown?<EyeOff size={18}/>:<Eye size={18}/>}</Button></div></div>;
}
export default function Home() {
 const [key,setKey] = useState(''), [mode,setMode] = useState('file'), [file,setFile] = useState<File|null>(null), [url,setUrl] = useState(''), [format,setFormat] = useState('mp3');
 const [ak,setAk]=useState(''), [sk,setSk]=useState(''), [bucket,setBucket]=useState(''), [region,setRegion]=useState('cn-beijing');
 const [smooth,setSmooth]=useState(false), [speaker,setSpeaker]=useState(false), [busy,setBusy]=useState(false), [status,setStatus]=useState('准备好录音，即可开始'), [error,setError]=useState(''), [task,setTask]=useState(''), [result,setResult]=useState<Result|null>(null), [text,setText]=useState(''), [object,setObject]=useState(''), [copied,setCopied]=useState(false);
 const [items,setItems]=useState<HistoryItem[]>([]), [historyError,setHistoryError]=useState(''), [historyId,setHistoryId]=useState(''), [outputName,setOutputName]=useState('录音转写'), [savedText,setSavedText]=useState(''), [historyLoading,setHistoryLoading]=useState(false);
 const [savedConfig,setSavedConfig]=useState<SavedSettings>({key:'',ak:'',sk:'',has_key:false,has_ak:false,has_sk:false,bucket:'',region:'cn-beijing'}), [configMessage,setConfigMessage]=useState('正在读取已保存配置…'), [configBusy,setConfigBusy]=useState(false);
 const stop=useRef(false), token=useRef('');
 const visible=useRef({status,text}); visible.current={status,text};
 useEffect(()=>{
  const ctx=(document as Document & {modelContext?:{registerTool:(tool:object,options:object)=>unknown}}).modelContext;
  if(!ctx?.registerTool)return;
  const life=new AbortController();
  try{Promise.resolve(ctx.registerTool({name:'read_transcript',description:'Read the current visible transcription text and status. Does not upload audio or expose credentials.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected empty input');return {...visible.current};}},{signal:life.signal})).catch(()=>{});}catch{}
  return ()=>life.abort();
 },[]);
 useEffect(()=>{void loadHistory();void loadSettings();setTask(localStorage.getItem('asr-task') || ''); return ()=>{stop.current=true;};},[]);
 async function api<T = Record<string, unknown>>(path:string, body:object|FormData) { if (!token.current) { const s=await fetch('/api/session'); token.current=(await s.json() as {token:string}).token; } const r=await fetch('/api/'+path,{method:'POST',signal:path.startsWith('settings/')?AbortSignal.timeout(15000):undefined,headers: body instanceof FormData ? {'X-Local-Token':token.current} : {'X-Local-Token':token.current,'Content-Type':'application/json'},body:body instanceof FormData ? body : JSON.stringify(body)}); const d=await r.json() as T & {error?:string;code?:string;logid?:string}; if(!r.ok) throw new Error([d.error,d.code && `状态码 ${d.code}`,d.logid && `日志编号 ${d.logid}`].filter(Boolean).join(' · ')); return d; }
 async function loadSettings(){try{const d=await api<SavedSettings>('settings/read',{});setSavedConfig(d);setKey(d.key);setAk(d.ak);setSk(d.sk);setBucket(d.bucket);setRegion(d.region);setConfigMessage(d.has_key?'已读取本地配置，可直接使用；填写新值并保存即可修改。':'填写后点击保存配置，下次打开自动使用。');}catch(e){setConfigMessage(e instanceof Error?e.message:'读取配置失败');}}
 async function saveSettings(){setConfigBusy(true);setConfigMessage('正在保存配置…');try{const d=await api<SavedSettings>('settings/save',{key,ak,sk,bucket,region});setSavedConfig(d);setKey(d.key);setAk(d.ak);setSk(d.sk);setBucket(d.bucket);setRegion(d.region);setConfigMessage('配置已保存到服务所在设备，下次打开自动使用。');return true;}catch(e){setConfigMessage('配置未保存：'+(e instanceof Error&&e.name==='TimeoutError'?'本地服务响应超时，请重启启动程序后重试。':e instanceof Error?e.message:'请检查本地服务是否运行。'));return false;}finally{setConfigBusy(false);}}
 async function loadHistory(){try{const d=await api<{items:HistoryItem[]}>('history/list',{});setItems(d.items);setHistoryError('');}catch{setHistoryError('历史记录读取失败，请确认本地服务已更新并运行。');}}
 async function saveEdits(){if(!historyId||!result||text===savedText)return;await api('history/edit',{id:historyId,text});setSavedText(text);await loadHistory();}
 async function openHistory(id:string){setHistoryLoading(true);setError('');try{await saveEdits();const d=await api<{record:HistoryItem}>('history/read',{id});const r=d.record;remember(r.id);setHistoryId(r.id);setOutputName(r.name);setResult(r.result||null);setText(r.text||'');setSavedText(r.text||'');setObject('');setStatus(r.result?'已打开历史转写：'+r.name:'已打开任务，可使用已保存的 Key 继续查询');}catch(e){setError(e instanceof Error?e.message:'读取失败');}finally{setHistoryLoading(false);}}
 function remember(id:string){setTask(id);localStorage.setItem('asr-task',id);}
 async function poll(id:string){ const until=Date.now()+4*3600000; while(!stop.current && Date.now()<until){const d=await api<{state:string;data:Result}>('query',{key,id});if(d.state==='done'){const saved=await api<{record:HistoryItem}>('history/read',{id});setHistoryId(id);setOutputName(saved.record.name);setResult(d.data);setText(saved.record.text||'');setSavedText(saved.record.text||'');setStatus('转写完成');await loadHistory();return;}setStatus(d.state==='queued'?'已提交，正在排队…':'正在识别录音…');await new Promise(r=>setTimeout(r,5000));}setStatus('已暂停查询，可随时继续。云端任务仍会执行。'); }
 async function start(){setError('');if(!key.trim()&&!savedConfig.has_key){setError('请先填写豆包语音 API Key。');return;}if(mode==='file'&&!file){setError('请先选择录音文件。');return;}if(mode==='file'&&!((ak.trim()||savedConfig.has_ak)&&(sk.trim()||savedConfig.has_sk)&&bucket.trim()&&region.trim())){setError('本地文件需要填写下方的 TOS 配置，或切换为音频链接。');return;}if(mode==='url'&&!url.trim()){setError('请填写音频下载直链。');return;}if(!(await saveSettings())){setError('请先完成配置保存后重试。');return;}try{await saveEdits();}catch{setError('当前文字保存失败，请先下载备份或重试保存。');return;}setBusy(true);stop.current=false;setHistoryId('');setSavedText('');setResult(null);setText('');setObject('');try{let link=url.trim(), fmt=format;if(mode==='file'&&file){setStatus('正在准备并上传录音，请保持页面打开…');const form=new FormData();form.append('file',file);Object.entries({ak,sk,bucket,region}).forEach(([k,v])=>form.append(k,v));const d=await api<{url:string;format:string;object:string}>('upload',form);link=d.url;fmt=d.format;setObject(d.object);}const id=createTaskId();remember(id);setStatus('正在提交识别任务…');const name=mode==='file'&&file?file.name:'链接录音';setOutputName(name);await api('submit',{key,url:link,format:fmt,id,smooth,speaker,name});await loadHistory();await poll(id);}catch(e){setError(e instanceof Error?e.message:'操作失败，请检查本地服务是否运行。');setStatus('操作未完成');}finally{setBusy(false);await loadHistory();}}
 async function resume(){if((!key.trim()&&!savedConfig.has_key)||!task.trim()){setError('请填写 API Key 和任务编号。');return;}setError('');if(!(await saveSettings())){setError('请先完成配置保存后重试。');return;}try{await saveEdits();}catch{setError('当前文字保存失败，请先下载备份或重试保存。');return;}setBusy(true);stop.current=false;remember(task.trim());try{await poll(task.trim());}catch(e){setError(e instanceof Error?e.message:'查询失败');setStatus('查询中断，可稍后重试');}finally{setBusy(false);await loadHistory();}}
 function download(kind:string){if(!result)return;const seg=(result.result?.utterances || []).filter(s=>s.start_time>=0&&s.end_time>s.start_time);let body=text;if(kind==='json')body=JSON.stringify(result,null,2);if(kind==='srt')body=seg.map((s,i)=>`${i+1}\n${stamp(s.start_time,true)} --> ${stamp(s.end_time,true)}\n${s.text}\n`).join('\n');if(kind==='timeline.txt')body=seg.map(s=>`[${stamp(s.start_time)}] ${s.additions?.speaker !== undefined ? '说话人 '+s.additions.speaker+'：' : ''}${s.text}`).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([body],{type:'text/plain;charset=utf-8'}));a.download=(outputName.replace(/\.[^.]+$/,'')||'录音转写')+'.'+kind;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
 return <main>
 <header className="top"><div className="brand"><span className="brandIcon"><AudioLines size={24}/></span><strong>听写工作台</strong></div><span className="badge"><i/> 本地运行</span></header>
 <section className="heading"><div><p className="eyebrow">DOUBAO SPEECH / 2.0</p><h1>把录音，变成文字。</h1><p className="sub">选择文件或粘贴链接，使用你的火山引擎账户转写。</p></div><a href="/使用说明.html" target="_blank" rel="noreferrer">首次使用与 TOS 配置 ↗</a></section>
 <div className="workspace"><section className="panel controls"><div className="sectionTitle"><span>01</span><h2>准备录音</h2></div>
 <fieldset disabled={busy||historyLoading||configBusy}>
 <SecretField id="speech-api-key" label="豆包语音 API Key" value={key} onChange={setKey}/>
 <p className="hint" role="status">{configMessage}</p><Button variant="outline" disabled={configBusy} onClick={saveSettings}>{configBusy?"正在保存…":"保存 / 更新配置"}</Button>
 <Tabs value={mode} onValueChange={v=>setMode(String(v))}><TabsList className="sourceTabs"><TabsTrigger value="file">本地文件</TabsTrigger><TabsTrigger value="url">音频链接</TabsTrigger></TabsList>
 <TabsContent value="file"><label className="drop"><FileAudio size={32}/><strong>{file?.name || '选择录音文件'}</strong><span>{file?`${(file.size/1024/1024).toFixed(1)} MB · 点击更换`:'MP3 / WAV / OGG / M4A / AAC · 小于 500 MB'}</span><input type="file" accept=".mp3,.wav,.ogg,.m4a,.aac" aria-label="选择录音文件" onChange={e=>{const f=e.target.files?.[0]||null;if(f&&f.size>=500*1024*1024){setError('请使用小于 500 MB 的文件。');setFile(null);}else {setFile(f);setError('');}}}/></label>
 <details className="tos"><summary>TOS 上传配置 <span>本地文件必填</span></summary><p>录音上传到你自己的私有存储桶，再交给豆包识别。</p><label className="field">存储桶名称<Input value={bucket} onChange={e=>setBucket(e.target.value)} placeholder="例如 my-recordings"/></label><label className="field">地域<Input value={region} onChange={e=>setRegion(e.target.value)} placeholder="例如 cn-beijing"/></label><label className="field">Access Key ID（AK）<Input type="text" autoComplete="off" spellCheck={false} placeholder="填写 Access Key ID" value={ak} onChange={e=>setAk(e.target.value)}/></label><SecretField id="tos-secret-key" label="Secret Access Key（SK）" value={sk} onChange={setSk}/><Button variant="outline" disabled={configBusy} onClick={saveSettings}>保存 / 更新配置</Button><br/><a href="/使用说明.html#tos" target="_blank" rel="noreferrer">还没有 TOS？查看配置步骤 ↗</a></details></TabsContent>
 <TabsContent value="url"><label className="field">音频下载直链<Input type="url" placeholder="https://…/audio.mp3" value={url} onChange={e=>setUrl(e.target.value)}/></label><label className="field">实际音频格式<Select value={format} onValueChange={v=>v&&setFormat(v)}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['mp3','wav','ogg'].map(f=><SelectItem key={f} value={f}>{f.toUpperCase()}</SelectItem>)}</SelectContent></Select></label><p className="hint">需要火山服务器可读取的文件链接，不支持带提取码的网盘分享页。</p></TabsContent></Tabs>
 <div className="options"><label><Checkbox checked={speaker} onCheckedChange={v=>setSpeaker(v===true)}/>区分说话人</label><label><Checkbox checked={smooth} onCheckedChange={v=>setSmooth(v===true)}/>去除口头语与重复表达</label></div>
 <p className="hint">自动添加标点和规范数字。保留原话时，请勿勾选去除口头语。</p>
 </fieldset><Button className="start" disabled={busy||historyLoading||configBusy} onClick={start}>{busy?<LoaderCircle className="spin"/>:<AudioLines/>}{busy?'处理中…':'开始转写'}{!busy&&<ArrowRight/>}</Button>
 <p className="privacy">点击后，录音将发送到你配置的火山服务，并按账户规则计费。配置以明文保存在服务所在设备的 data/config.json，文件权限仅允许服务运行用户读写；局域网访问者可通过页面查看和修改；不写入历史或安装包。</p>
 </section>
 <section className="panel result"><div className="sectionTitle"><span>02</span><h2>转写文字</h2><span className="count">{text.length.toLocaleString()} 字符</span></div><div className={'status '+(error?'failed':'')} role="status">{busy&&<LoaderCircle size={16} className="spin"/>}{status}</div>{error&&<p className="error" role="alert">{error}</p>}
 {result?<><textarea className="transcript" aria-label="转写文字，可编辑" value={text} onChange={e=>setText(e.target.value)}/><div className="downloads"><Button variant="outline" disabled={!historyId||text===savedText||busy||historyLoading} onClick={async()=>{try{await saveEdits();}catch{setError('保存失败，请重试或下载文字备份。');}}}>{text===savedText?'已保存到历史':'保存修改'}</Button><Button onClick={()=>download('txt')}><Download/>下载文字</Button><Button variant="outline" onClick={async()=>{try{await copyText(text);setCopied(true);setTimeout(()=>setCopied(false),2000);}catch{setError('复制失败，请选中文字复制。');}}}><Copy/>{copied?'已复制':'复制'}</Button><Button variant="outline" disabled={!result.result?.utterances?.length} onClick={()=>download('srt')}>字幕 SRT</Button><Button variant="outline" disabled={!result.result?.utterances?.length} onClick={()=>download('timeline.txt')}>时间戳文本</Button><Button variant="ghost" onClick={()=>download('json')}>原始结果</Button></div><p className="hint">识别结果自动保存；编辑后请点击“保存修改”。字幕和时间戳文本使用原始分句结果。</p></>:<div className="empty"><AudioLines size={48} strokeWidth={1}/><h3>{busy?'正在听你的录音':'文字将在这里出现'}</h3><p>{busy?'长录音可能需要较长时间，请保持本地服务运行。':'完成后可编辑、复制，或下载为文字与字幕。'}</p></div>}
 <details className="resume" open={!!task}><summary>任务编号与继续查询</summary><p className="hint">任务编号保存在本机浏览器；关闭页面后，使用已保存的 Key 即可查询。暂停查询不会取消云端任务。</p><div className="resumeRow"><Input aria-label="任务编号" value={task} onChange={e=>setTask(e.target.value)} disabled={busy||historyLoading||configBusy} placeholder="粘贴已有任务编号"/><Button variant="outline" disabled={busy||historyLoading||configBusy} onClick={resume}>继续查询</Button>{busy&&<Button variant="ghost" onClick={()=>{stop.current=true;setStatus('等待本次请求返回后暂停…');}}>暂停</Button>}</div></details>
 {object&&<p className="hint object">已上传：{object}。云端文件保留在你的 TOS 中，请按使用说明配置到期清理。</p>}
 </section></div>
 <section className="panel historyPanel"><div className="sectionTitle"><span>03</span><h2>历史记录</h2><span className="count">{items.length} 条</span><Button variant="ghost" disabled={busy||historyLoading||configBusy} onClick={loadHistory}>刷新列表</Button></div><p className="hint">保存在服务所在设备，多台设备共用。查看已完成记录无需 Key；未完成任务可打开后继续查询。录音文件与密钥不会存入历史。</p>{historyError&&<p className="error" role="alert">{historyError}</p>}{!items.length&&!historyError?<p className="historyEmpty">还没有历史记录。新提交的录音任务会自动出现在这里。</p>:<div className="historyList">{items.map(item=><button className={'historyRow '+(historyId===item.id?'selected':'')} key={item.id} disabled={busy||historyLoading||configBusy} onClick={()=>openHistory(item.id)}><FileAudio size={22}/><div><strong>{item.name}</strong><p>{item.preview||'尚未取得转写文字'}</p><small>{new Date(item.created_at).toLocaleString('zh-CN')} · {item.characters||0} 字符</small></div><span className={'historyState '+(item.state==='done'?'done':'')}>{stateLabel[item.state]||'待查询'}</span><ArrowRight size={18}/></button>)}</div>}</section><footer>录音文件识别 2.0 <span>支持本机与局域网访问 · 识别在火山云端</span></footer>
 </main>;
}
